# Generated by Django 6.1 on 2026-08-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_class_department_term_assessment_student_enrollment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='class_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='teacher',
            name='teacher_id',
            field=models.TextField(default=''),
        ),
    ]
