# Generated by Django 6.1 on 2026-08-23 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_class_class_id_student_student_id_teacher_teacher_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='class_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='teacher_id',
            field=models.TextField(),
        ),
    ]
