# Generated by Django 6.1 on 2026-08-23 12:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_class_class_id_alter_student_student_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('building', models.CharField(max_length=255)),
                ('campus', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='class',
            name='room_number',
        ),
        migrations.AddField(
            model_name='class',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapp.room'),
        ),
    ]
