# Generated by Django 6.1 on 2026-08-24 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_remove_student_enrollment_date_student_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='batch',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
