# Generated by Django 6.1 on 2026-08-25 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_class_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='credits',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='gpa',
            field=models.DecimalField(default=0),
        ),
    ]
