# Generated by Django 6.1 on 2026-08-25 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_enrollment_credits_enrollment_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='gpa',
            field=models.FloatField(default=0.0),
        ),
    ]
