# Generated by Django 6.1 on 2026-08-25 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_enrollment_gpa'),
    ]

    operations = [
        migrations.AddField(
            model_name='enrollment',
            name='final_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
