# Generated by Django 6.1 on 2026-08-25 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_enrollment_final_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='schedule',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
