# Generated by Django 6.1 on 2026-08-27 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_class_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='max_score',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
        migrations.AlterField(
            model_name='studentscore',
            name='score',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
